title: HARSH WARDHAN NATH MISHRA
logo: ![image alt](https://github.com/harshwardhannathmishra-boop/harshwardhan.github.io/blob/main/IMAGES/MY%20PIC%20PASPORT%20SIZE.jpg?raw=true)
theme: jekyll-theme-minimal
