title: Harsh wardhan Nath Mishra's Portfolio
email: harshwardhannathmishra@gmail.com
description: >
  A portfolio showcasing the projects and experiences of Rounak Mishra, a Computer Science and Engineering student at Galgotias University.
baseurl: "" # Leave empty for root
url: "https://rounakmishra06.github.io/MyPortfolio"
twitter_username: rounakmishra06
github_username: rounakmishra06

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json

defaults:
  - scope:
      path: ""
    values:
      layout: default
